### ISSUE TITLE
Do not send private keys to any other host!

### ISSUE THREAD

**Issue by L3P3** [rajatjindal/github-app-installations#4]
Your readme instructs people to send to you their private key but that should NEVER be sent anywhere!

Find a solution to this which does not require sending it anywhere or this repo will be reported.

**Comment by rajatjindal** [comment]
ack !! I do not control that hosting either, but its deployed as openfaas function on a public cloud provided by one of open source legend and github star alexellis.

but in anycase i will implement a local solution for it, and use that instead of sending private key to remote server.

thanks for reporting.

**Comment by L3P3** [comment]
Please add a disclaimer NOW that people should NEVER send their private keys to anywhere if it is important! If people work for companies and send their keys they can be fired and even more. Add a disclaimer above the instruction NOW.

**Comment by rajatjindal** [comment]
Please feel free to submit a PR. I am happy to merge.

**Comment by L3P3** [comment]
I did.

https://github.com/rajatjindal/github-app-installations/pull/5

**Comment by rajatjindal** [comment]
removed the remote url from documentation. will move this to locally executable function at a later stage.

**Comment by rajatjindal** [comment]
thanks again for reporting this issue and submitting the PR

**Comment by L3P3** [comment]
Yea, sorry for annoying but I think people could loose their jobs by things like these. :sweat_smile:

**Comment by L3P3** [comment]
Hello, no matter what you wrote here, your readme still instructs people to send their private key without a disclaimer.
You fix this now or I will take action by myself, please understand.

**Comment by rajatjindal** [comment]
Hi @L3P3 

While I appreciate and understand your original report, and I took action and removed the remote URL from docs, I don't think its fair at this stage to force me to add a disclaimer.

if at all, user will be sending the credentials to their localhost. I don't see how that is a security issue. 

no offense, but if you are not satisfied with the response, please feel free to take the action that you want to take. 

I do plan to change this code a bit (user would still need to send private key to their localhost), but I would like to do that when I have bandwidth.

Thanks for understanding
Rajat Jindal

**Comment by L3P3** [comment]
Sorry, I missed that the address was changed to localhost. :laughing:
No, it is fine like that!
